CREATE   FUNCTION App.fnParsePrimaryKey(@PK NVARCHAR(50)) RETURNS BIT
AS
	BEGIN
		DECLARE @ParseOk BIT = 0;

		SET @ParseOk = CASE		
				WHEN CHARINDEX('"', @PK) > 0 THEN 0	
				WHEN CHARINDEX('''', @PK) > 0 THEN 0	
				WHEN CHARINDEX(',', @PK) > 0 THEN 0	
				WHEN CHARINDEX('<', @PK) > 0 THEN 0	
				WHEN CHARINDEX('>', @PK) > 0 THEN 0	
				WHEN CHARINDEX('@', @PK) > 0 THEN 0	
				WHEN CHARINDEX(':', @PK) > 0 THEN 0	
				WHEN CHARINDEX('*', @PK) > 0 THEN 0	
				WHEN CHARINDEX('', @PK) > 0 THEN 0	
				WHEN CHARINDEX('', @PK) > 0 THEN 0	
				WHEN CHARINDEX('{', @PK) > 0 THEN 0	
				WHEN CHARINDEX('}', @PK) > 0 THEN 0	
				--WHEN CHARINDEX('_', @PK) > 0 THEN 0	
				--WHEN CHARINDEX('&', @PK) > 0 THEN 0	
				--WHEN CHARINDEX('/', @PK) > 0 THEN 0	
				--WHEN CHARINDEX('\', @PK) > 0 THEN 0	
				--WHEN CHARINDEX(' ', @PK) > 0 THEN 0	
				--WHEN CHARINDEX('(', @PK) > 0 THEN 0	
				--WHEN CHARINDEX(')', @PK) > 0 THEN 0	
				ELSE 1 END;

		RETURN @ParseOk;
	END
