#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeControl.Node
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="tcNodeDb4_1_1")]
	public partial class dbNodeCashDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public dbNodeCashDataContext() : 
				base(global::TradeControl.Node.Properties.Settings.Default.tcNodeDb4_1_1ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbNodeCashDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbNodeCashDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbNodeCashDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbNodeCashDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<vwChangeCollection> vwChangeCollections
		{
			get
			{
				return this.GetTable<vwChangeCollection>();
			}
		}
		
		public System.Data.Linq.Table<vwTaxCode> vwTaxCodes
		{
			get
			{
				return this.GetTable<vwTaxCode>();
			}
		}
		
		public System.Data.Linq.Table<vwCashCode> vwCashCodes
		{
			get
			{
				return this.GetTable<vwCashCode>();
			}
		}
		
		public System.Data.Linq.Table<vwUserCredential> vwUserCredentials
		{
			get
			{
				return this.GetTable<vwUserCredential>();
			}
		}
		
		public System.Data.Linq.Table<vwTransferCashCode> vwTransferCashCodes
		{
			get
			{
				return this.GetTable<vwTransferCashCode>();
			}
		}
		
		public System.Data.Linq.Table<vwInvoicedReceipts> vwInvoicedReceipts
		{
			get
			{
				return this.GetTable<vwInvoicedReceipts>();
			}
		}
		
		public System.Data.Linq.Table<vwInvoicedPayments> vwInvoicedPayments
		{
			get
			{
				return this.GetTable<vwInvoicedPayments>();
			}
		}
		
		public System.Data.Linq.Table<vwNamespace> vwNamespaces
		{
			get
			{
				return this.GetTable<vwNamespace>();
			}
		}
		
		public System.Data.Linq.Table<vwWallet> vwWallets
		{
			get
			{
				return this.GetTable<vwWallet>();
			}
		}
		
		public System.Data.Linq.Table<vwCashStatement> vwCashStatements
		{
			get
			{
				return this.GetTable<vwCashStatement>();
			}
		}
		
		public System.Data.Linq.Table<vwSubjectList> vwSubjectLists
		{
			get
			{
				return this.GetTable<vwSubjectList>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="App.proc_EventLog")]
		public int proc_EventLog([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EventMessage", DbType="NVarChar(MAX)")] string eventMessage, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EventTypeCode", DbType="SmallInt")] System.Nullable<short> eventTypeCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LogCode", DbType="NVarChar(20)")] ref string logCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), eventMessage, eventTypeCode, logCode);
			logCode = ((string)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Cash.fnChange", IsComposable=true)]
		public IQueryable<fnChangeResult> fnChange([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountCode", DbType="NVarChar(10)")] string accountCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KeyName", DbType="NVarChar(50)")] string keyName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChangeTypeCode", DbType="SmallInt")] System.Nullable<short> changeTypeCode)
		{
			return this.CreateMethodCallQuery<fnChangeResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), accountCode, keyName, changeTypeCode);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Cash.fnChangeTx", IsComposable=true)]
		public IQueryable<fnChangeTxResult> fnChangeTx([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaymentAddress", DbType="NVarChar(42)")] string paymentAddress)
		{
			return this.CreateMethodCallQuery<fnChangeTxResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), paymentAddress);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Cash.fnChangeUnassigned", IsComposable=true)]
		public IQueryable<fnChangeUnassignedResult> fnChangeUnassigned([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountCode", DbType="NVarChar(10)")] string accountCode)
		{
			return this.CreateMethodCallQuery<fnChangeUnassignedResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), accountCode);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Cash.fnKeyAddresses", IsComposable=true)]
		public IQueryable<fnKeyAddressesResult> fnKeyAddresses([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountCode", DbType="NVarChar(10)")] string accountCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KeyName", DbType="NVarChar(50)")] string keyName)
		{
			return this.CreateMethodCallQuery<fnKeyAddressesResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), accountCode, keyName);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Cash.fnKeyNameBalance", IsComposable=true)]
		public System.Nullable<double> fnKeyNameBalance([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountCode", DbType="NVarChar(10)")] string accountCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KeyName", DbType="NVarChar(50)")] string keyName)
		{
			return ((System.Nullable<double>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), accountCode, keyName).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Cash.fnNamespaceBalance", IsComposable=true)]
		public System.Nullable<double> fnNamespaceBalance([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountCode", DbType="NVarChar(10)")] string accountCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KeyName", DbType="NVarChar(50)")] string keyName)
		{
			return ((System.Nullable<double>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), accountCode, keyName).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Cash.fnTx", IsComposable=true)]
		public IQueryable<fnTxResult> fnTx([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountCode", DbType="NVarChar(10)")] string accountCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KeyName", DbType="NVarChar(50)")] string keyName)
		{
			return this.CreateMethodCallQuery<fnTxResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), accountCode, keyName);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Subject.proc_AccountKeyRename")]
		public int proc_AccountKeyRename([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountCode", DbType="NVarChar(10)")] string accountCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OldKeyName", DbType="NVarChar(50)")] string oldKeyName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NewKeyName", DbType="NVarChar(50)")] string newKeyName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KeyNamespace", DbType="NVarChar(1024)")] ref string keyNamespace)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), accountCode, oldKeyName, newKeyName, keyNamespace);
			keyNamespace = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Subject.proc_AccountKeyDelete")]
		public int proc_AccountKeyDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountCode", DbType="NVarChar(10)")] string accountCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KeyName", DbType="NVarChar(50)")] string keyName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), accountCode, keyName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Subject.proc_AccountKeyAdd")]
		public int proc_AccountKeyAdd([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountCode", DbType="NVarChar(10)")] string accountCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParentName", DbType="NVarChar(50)")] string parentName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChildName", DbType="NVarChar(50)")] string childName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChildHDPath", DbType="NVarChar(50)")] ref string childHDPath)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), accountCode, parentName, childName, childHDPath);
			childHDPath = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Subject.proc_BalanceToPay")]
		public int proc_BalanceToPay([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubjectCode", DbType="NVarChar(10)")] string subjectCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Balance", DbType="Decimal(18,5)")] ref System.Nullable<decimal> balance)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), subjectCode, balance);
			balance = ((System.Nullable<decimal>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Cash.proc_ChangeAddressIndex")]
		public int proc_ChangeAddressIndex([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountCode", DbType="NVarChar(10)")] string accountCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KeyName", DbType="NVarChar(50)")] string keyName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChangeTypeCode", DbType="SmallInt")] System.Nullable<short> changeTypeCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AddressIndex", DbType="Int")] ref System.Nullable<int> addressIndex)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), accountCode, keyName, changeTypeCode, addressIndex);
			addressIndex = ((System.Nullable<int>)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Cash.proc_ChangeTxAdd")]
		public int proc_ChangeTxAdd([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaymentAddress", DbType="NVarChar(42)")] string paymentAddress, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TxId", DbType="NVarChar(64)")] string txId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TxStatusCode", DbType="SmallInt")] System.Nullable<short> txStatusCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MoneyIn", DbType="Decimal(18,5)")] System.Nullable<decimal> moneyIn, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Confirmations", DbType="Int")] System.Nullable<int> confirmations, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TxMessage", DbType="NVarChar(50)")] string txMessage)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), paymentAddress, txId, txStatusCode, moneyIn, confirmations, txMessage);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Cash.proc_ChangeAssign")]
		public int proc_ChangeAssign([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountCode", DbType="NVarChar(10)")] string accountCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KeyName", DbType="NVarChar(50)")] string keyName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaymentAddress", DbType="NVarChar(42)")] string paymentAddress, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="InvoiceNumber", DbType="NVarChar(20)")] string invoiceNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Note", DbType="NVarChar(256)")] string note)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), accountCode, keyName, paymentAddress, invoiceNumber, note);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Cash.proc_ChangeDelete")]
		public int proc_ChangeDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaymentAddress", DbType="NVarChar(42)")] string paymentAddress)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), paymentAddress);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Cash.proc_ChangeNew")]
		public int proc_ChangeNew([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountCode", DbType="NVarChar(10)")] string accountCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KeyName", DbType="NVarChar(50)")] string keyName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChangeTypeCode", DbType="SmallInt")] System.Nullable<short> changeTypeCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaymentAddress", DbType="NVarChar(42)")] string paymentAddress, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AddressIndex", DbType="Int")] System.Nullable<int> addressIndex, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="InvoiceNumber", DbType="NVarChar(20)")] string invoiceNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Note", DbType="NVarChar(256)")] string note)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), accountCode, keyName, changeTypeCode, paymentAddress, addressIndex, invoiceNumber, note);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Cash.proc_ChangeNote")]
		public int proc_ChangeNote([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaymentAddress", DbType="NVarChar(42)")] string paymentAddress, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Note", DbType="NVarChar(256)")] string note)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), paymentAddress, note);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Cash.proc_PayAccrual")]
		public int proc_PayAccrual([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaymentCode", DbType="NVarChar(20)")] string paymentCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), paymentCode);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Cash.proc_PaymentPost")]
		public int proc_PaymentPost()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Cash.proc_TxPayOutTransfer")]
		public int proc_TxPayOutTransfer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaymentAddress", DbType="NVarChar(42)")] string paymentAddress, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TxId", DbType="NVarChar(64)")] string txId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Spent", DbType="Decimal(18,5)")] System.Nullable<decimal> spent, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MinerFee", DbType="Decimal(18,5)")] System.Nullable<decimal> minerFee, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CashCode", DbType="NVarChar(50)")] string cashCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaymentReference", DbType="NVarChar(50)")] string paymentReference)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), paymentAddress, txId, spent, minerFee, cashCode, paymentReference);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Cash.proc_TxPayAccount")]
		public int proc_TxPayAccount([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaymentAddress", DbType="NVarChar(42)")] string paymentAddress, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TxId", DbType="NVarChar(64)")] string txId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Spent", DbType="Decimal(18,5)")] System.Nullable<decimal> spent, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MinerFee", DbType="Decimal(18,5)")] System.Nullable<decimal> minerFee, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubjectCode", DbType="NVarChar(10)")] string subjectCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), paymentAddress, txId, spent, minerFee, subjectCode);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Cash.proc_TxPayIn")]
		public int proc_TxPayIn([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountCode", DbType="NVarChar(10)")] string accountCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaymentAddress", DbType="NVarChar(42)")] string paymentAddress, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TxId", DbType="NVarChar(64)")] string txId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubjectCode", DbType="NVarChar(10)")] string subjectCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CashCode", DbType="NVarChar(50)")] string cashCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaidOn", DbType="DateTime")] System.Nullable<System.DateTime> paidOn, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaymentReference", DbType="NVarChar(50)")] string paymentReference, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaymentCode", DbType="NVarChar(20)")] ref string paymentCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), accountCode, paymentAddress, txId, subjectCode, cashCode, paidOn, paymentReference, paymentCode);
			paymentCode = ((string)(result.GetParameterValue(7)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Cash.proc_TxPayInChange")]
		public int proc_TxPayInChange([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountCode", DbType="NVarChar(10)")] string accountCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaymentAddress", DbType="NVarChar(42)")] string paymentAddress, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TxId", DbType="NVarChar(64)")] string txId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubjectCode", DbType="NVarChar(10)")] string subjectCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CashCode", DbType="NVarChar(50)")] string cashCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaymentReference", DbType="NVarChar(50)")] string paymentReference)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), accountCode, paymentAddress, txId, subjectCode, cashCode, paymentReference);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Cash.proc_TxPayOutInvoice")]
		public int proc_TxPayOutInvoice([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubjectCode", DbType="NVarChar(10)")] string subjectCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CashCode", DbType="NVarChar(50)")] string cashCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TaxCode", DbType="NVarChar(10)")] string taxCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ItemReference", DbType="NVarChar(50)")] string itemReference, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaidOutValue", DbType="Decimal(18,5)")] System.Nullable<decimal> paidOutValue)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), subjectCode, cashCode, taxCode, itemReference, paidOutValue);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Cash.proc_TxPayOutMisc")]
		public int proc_TxPayOutMisc([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaymentAddress", DbType="NVarChar(42)")] string paymentAddress, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TxId", DbType="NVarChar(64)")] string txId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Spent", DbType="Decimal(18,5)")] System.Nullable<decimal> spent, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MinerFee", DbType="Decimal(18,5)")] System.Nullable<decimal> minerFee, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubjectCode", DbType="NVarChar(10)")] string subjectCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CashCode", DbType="NVarChar(50)")] string cashCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TaxCode", DbType="NVarChar(10)")] string taxCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaymentReference", DbType="NVarChar(50)")] string paymentReference)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), paymentAddress, txId, spent, minerFee, subjectCode, cashCode, taxCode, paymentReference);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Subject.proc_WalletInitialise")]
		public int proc_WalletInitialise()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Cash.vwChangeCollection")]
	public partial class vwChangeCollection
	{
		
		private string _PaymentAddress;
		
		private string _FullHDPath;
		
		public vwChangeCollection()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentAddress", DbType="NVarChar(42) NOT NULL", CanBeNull=false)]
		public string PaymentAddress
		{
			get
			{
				return this._PaymentAddress;
			}
			set
			{
				if ((this._PaymentAddress != value))
				{
					this._PaymentAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullHDPath", DbType="NVarChar(256)")]
		public string FullHDPath
		{
			get
			{
				return this._FullHDPath;
			}
			set
			{
				if ((this._FullHDPath != value))
				{
					this._FullHDPath = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="App.vwTaxCodes")]
	public partial class vwTaxCode
	{
		
		private string _TaxCode;
		
		private string _TaxDescription;
		
		private string _TaxType;
		
		public vwTaxCode()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxCode", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string TaxCode
		{
			get
			{
				return this._TaxCode;
			}
			set
			{
				if ((this._TaxCode != value))
				{
					this._TaxCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxDescription", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TaxDescription
		{
			get
			{
				return this._TaxDescription;
			}
			set
			{
				if ((this._TaxDescription != value))
				{
					this._TaxDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxType", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string TaxType
		{
			get
			{
				return this._TaxType;
			}
			set
			{
				if ((this._TaxType != value))
				{
					this._TaxType = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Cash.vwCodeLookup")]
	public partial class vwCashCode
	{
		
		private string _CashCode;
		
		private string _CashDescription;
		
		private string _Category;
		
		private short _CashModeCode;
		
		private string _CashMode;
		
		private string _TaxCode;
		
		public vwCashCode()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CashCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CashCode
		{
			get
			{
				return this._CashCode;
			}
			set
			{
				if ((this._CashCode != value))
				{
					this._CashCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CashDescription", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string CashDescription
		{
			get
			{
				return this._CashDescription;
			}
			set
			{
				if ((this._CashDescription != value))
				{
					this._CashDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this._Category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CashModeCode", DbType="SmallInt NOT NULL")]
		public short CashModeCode
		{
			get
			{
				return this._CashModeCode;
			}
			set
			{
				if ((this._CashModeCode != value))
				{
					this._CashModeCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CashMode", DbType="NVarChar(10)")]
		public string CashMode
		{
			get
			{
				return this._CashMode;
			}
			set
			{
				if ((this._CashMode != value))
				{
					this._CashMode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxCode", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string TaxCode
		{
			get
			{
				return this._TaxCode;
			}
			set
			{
				if ((this._TaxCode != value))
				{
					this._TaxCode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Usr.vwCredentials")]
	public partial class vwUserCredential
	{
		
		private string _UserId;
		
		private string _UserName;
		
		private string _LogonName;
		
		private bool _IsAdministrator;
		
		public vwUserCredential()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogonName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LogonName
		{
			get
			{
				return this._LogonName;
			}
			set
			{
				if ((this._LogonName != value))
				{
					this._LogonName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAdministrator", DbType="Bit NOT NULL")]
		public bool IsAdministrator
		{
			get
			{
				return this._IsAdministrator;
			}
			set
			{
				if ((this._IsAdministrator != value))
				{
					this._IsAdministrator = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Cash.vwTransferCodeLookup")]
	public partial class vwTransferCashCode
	{
		
		private string _CashCode;
		
		private string _CashDescription;
		
		private string _Category;
		
		private string _CashMode;
		
		private short _CashModeCode;
		
		public vwTransferCashCode()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CashCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CashCode
		{
			get
			{
				return this._CashCode;
			}
			set
			{
				if ((this._CashCode != value))
				{
					this._CashCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CashDescription", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string CashDescription
		{
			get
			{
				return this._CashDescription;
			}
			set
			{
				if ((this._CashDescription != value))
				{
					this._CashDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this._Category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CashMode", DbType="NVarChar(10)")]
		public string CashMode
		{
			get
			{
				return this._CashMode;
			}
			set
			{
				if ((this._CashMode != value))
				{
					this._CashMode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CashModeCode", DbType="SmallInt NOT NULL")]
		public short CashModeCode
		{
			get
			{
				return this._CashModeCode;
			}
			set
			{
				if ((this._CashModeCode != value))
				{
					this._CashModeCode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Invoice.vwRegisterSalesOverdue")]
	public partial class vwInvoicedReceipts
	{
		
		private string _InvoiceNumber;
		
		private string _SubjectCode;
		
		private string _SubjectName;
		
		private short _InvoiceTypeCode;
		
		private short _InvoiceStatusCode;
		
		private string _InvoiceStatus;
		
		private string _InvoiceType;
		
		private System.Nullable<int> _UnpaidDays;
		
		private System.DateTime _InvoicedOn;
		
		private System.DateTime _DueOn;
		
		private System.DateTime _ExpectedOn;
		
		private System.Nullable<decimal> _InvoiceValue;
		
		private System.Nullable<decimal> _TaxValue;
		
		private System.Nullable<decimal> _UnpaidValue;
		
		private string _PaymentAddress;
		
		private string _PaymentTerms;
		
		private string _Notes;
		
		public vwInvoicedReceipts()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNumber", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string InvoiceNumber
		{
			get
			{
				return this._InvoiceNumber;
			}
			set
			{
				if ((this._InvoiceNumber != value))
				{
					this._InvoiceNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubjectCode", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string SubjectCode
		{
			get
			{
				return this._SubjectCode;
			}
			set
			{
				if ((this._SubjectCode != value))
				{
					this._SubjectCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubjectName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string SubjectName
		{
			get
			{
				return this._SubjectName;
			}
			set
			{
				if ((this._SubjectName != value))
				{
					this._SubjectName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceTypeCode", DbType="SmallInt NOT NULL")]
		public short InvoiceTypeCode
		{
			get
			{
				return this._InvoiceTypeCode;
			}
			set
			{
				if ((this._InvoiceTypeCode != value))
				{
					this._InvoiceTypeCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceStatusCode", DbType="SmallInt NOT NULL")]
		public short InvoiceStatusCode
		{
			get
			{
				return this._InvoiceStatusCode;
			}
			set
			{
				if ((this._InvoiceStatusCode != value))
				{
					this._InvoiceStatusCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceStatus", DbType="NVarChar(50)")]
		public string InvoiceStatus
		{
			get
			{
				return this._InvoiceStatus;
			}
			set
			{
				if ((this._InvoiceStatus != value))
				{
					this._InvoiceStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceType", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string InvoiceType
		{
			get
			{
				return this._InvoiceType;
			}
			set
			{
				if ((this._InvoiceType != value))
				{
					this._InvoiceType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnpaidDays", DbType="Int")]
		public System.Nullable<int> UnpaidDays
		{
			get
			{
				return this._UnpaidDays;
			}
			set
			{
				if ((this._UnpaidDays != value))
				{
					this._UnpaidDays = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoicedOn", DbType="DateTime NOT NULL")]
		public System.DateTime InvoicedOn
		{
			get
			{
				return this._InvoicedOn;
			}
			set
			{
				if ((this._InvoicedOn != value))
				{
					this._InvoicedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DueOn", DbType="DateTime NOT NULL")]
		public System.DateTime DueOn
		{
			get
			{
				return this._DueOn;
			}
			set
			{
				if ((this._DueOn != value))
				{
					this._DueOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpectedOn", DbType="DateTime NOT NULL")]
		public System.DateTime ExpectedOn
		{
			get
			{
				return this._ExpectedOn;
			}
			set
			{
				if ((this._ExpectedOn != value))
				{
					this._ExpectedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceValue", DbType="Decimal(20,5)")]
		public System.Nullable<decimal> InvoiceValue
		{
			get
			{
				return this._InvoiceValue;
			}
			set
			{
				if ((this._InvoiceValue != value))
				{
					this._InvoiceValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxValue", DbType="Decimal(20,5)")]
		public System.Nullable<decimal> TaxValue
		{
			get
			{
				return this._TaxValue;
			}
			set
			{
				if ((this._TaxValue != value))
				{
					this._TaxValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnpaidValue", DbType="Decimal(22,5)")]
		public System.Nullable<decimal> UnpaidValue
		{
			get
			{
				return this._UnpaidValue;
			}
			set
			{
				if ((this._UnpaidValue != value))
				{
					this._UnpaidValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentAddress", DbType="NVarChar(42)")]
		public string PaymentAddress
		{
			get
			{
				return this._PaymentAddress;
			}
			set
			{
				if ((this._PaymentAddress != value))
				{
					this._PaymentAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentTerms", DbType="NVarChar(100)")]
		public string PaymentTerms
		{
			get
			{
				return this._PaymentTerms;
			}
			set
			{
				if ((this._PaymentTerms != value))
				{
					this._PaymentTerms = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this._Notes = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Invoice.vwRegisterPurchasesOverdue")]
	public partial class vwInvoicedPayments
	{
		
		private string _InvoiceNumber;
		
		private string _SubjectCode;
		
		private string _SubjectName;
		
		private short _InvoiceTypeCode;
		
		private short _InvoiceStatusCode;
		
		private string _InvoiceStatus;
		
		private string _InvoiceType;
		
		private System.Nullable<int> _UnpaidDays;
		
		private System.DateTime _InvoicedOn;
		
		private System.DateTime _DueOn;
		
		private System.DateTime _ExpectedOn;
		
		private System.Nullable<decimal> _InvoiceValue;
		
		private System.Nullable<decimal> _TaxValue;
		
		private System.Nullable<decimal> _UnpaidValue;
		
		private string _PaymentAddress;
		
		private string _PaymentTerms;
		
		private string _Notes;
		
		public vwInvoicedPayments()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNumber", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string InvoiceNumber
		{
			get
			{
				return this._InvoiceNumber;
			}
			set
			{
				if ((this._InvoiceNumber != value))
				{
					this._InvoiceNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubjectCode", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string SubjectCode
		{
			get
			{
				return this._SubjectCode;
			}
			set
			{
				if ((this._SubjectCode != value))
				{
					this._SubjectCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubjectName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string SubjectName
		{
			get
			{
				return this._SubjectName;
			}
			set
			{
				if ((this._SubjectName != value))
				{
					this._SubjectName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceTypeCode", DbType="SmallInt NOT NULL")]
		public short InvoiceTypeCode
		{
			get
			{
				return this._InvoiceTypeCode;
			}
			set
			{
				if ((this._InvoiceTypeCode != value))
				{
					this._InvoiceTypeCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceStatusCode", DbType="SmallInt NOT NULL")]
		public short InvoiceStatusCode
		{
			get
			{
				return this._InvoiceStatusCode;
			}
			set
			{
				if ((this._InvoiceStatusCode != value))
				{
					this._InvoiceStatusCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceStatus", DbType="NVarChar(50)")]
		public string InvoiceStatus
		{
			get
			{
				return this._InvoiceStatus;
			}
			set
			{
				if ((this._InvoiceStatus != value))
				{
					this._InvoiceStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceType", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string InvoiceType
		{
			get
			{
				return this._InvoiceType;
			}
			set
			{
				if ((this._InvoiceType != value))
				{
					this._InvoiceType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnpaidDays", DbType="Int")]
		public System.Nullable<int> UnpaidDays
		{
			get
			{
				return this._UnpaidDays;
			}
			set
			{
				if ((this._UnpaidDays != value))
				{
					this._UnpaidDays = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoicedOn", DbType="DateTime NOT NULL")]
		public System.DateTime InvoicedOn
		{
			get
			{
				return this._InvoicedOn;
			}
			set
			{
				if ((this._InvoicedOn != value))
				{
					this._InvoicedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DueOn", DbType="DateTime NOT NULL")]
		public System.DateTime DueOn
		{
			get
			{
				return this._DueOn;
			}
			set
			{
				if ((this._DueOn != value))
				{
					this._DueOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpectedOn", DbType="DateTime NOT NULL")]
		public System.DateTime ExpectedOn
		{
			get
			{
				return this._ExpectedOn;
			}
			set
			{
				if ((this._ExpectedOn != value))
				{
					this._ExpectedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceValue", DbType="Decimal(20,5)")]
		public System.Nullable<decimal> InvoiceValue
		{
			get
			{
				return this._InvoiceValue;
			}
			set
			{
				if ((this._InvoiceValue != value))
				{
					this._InvoiceValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxValue", DbType="Decimal(20,5)")]
		public System.Nullable<decimal> TaxValue
		{
			get
			{
				return this._TaxValue;
			}
			set
			{
				if ((this._TaxValue != value))
				{
					this._TaxValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnpaidValue", DbType="Decimal(22,5)")]
		public System.Nullable<decimal> UnpaidValue
		{
			get
			{
				return this._UnpaidValue;
			}
			set
			{
				if ((this._UnpaidValue != value))
				{
					this._UnpaidValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentAddress", DbType="NVarChar(42)")]
		public string PaymentAddress
		{
			get
			{
				return this._PaymentAddress;
			}
			set
			{
				if ((this._PaymentAddress != value))
				{
					this._PaymentAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentTerms", DbType="NVarChar(100)")]
		public string PaymentTerms
		{
			get
			{
				return this._PaymentTerms;
			}
			set
			{
				if ((this._PaymentTerms != value))
				{
					this._PaymentTerms = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this._Notes = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Subject.vwNamespace")]
	public partial class vwNamespace
	{
		
		private string _AccountCode;
		
		private string _ParentHDPath;
		
		private string _ChildHDPath;
		
		private string _KeyName;
		
		private string _KeyNamespace;
		
		private System.Nullable<short> _KeyLevel;
		
		private System.Nullable<int> _ReceiptIndex;
		
		private System.Nullable<int> _ChangeIndex;
		
		public vwNamespace()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountCode", DbType="NVarChar(10)")]
		public string AccountCode
		{
			get
			{
				return this._AccountCode;
			}
			set
			{
				if ((this._AccountCode != value))
				{
					this._AccountCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentHDPath", DbType="NVarChar(61) NOT NULL", CanBeNull=false)]
		public string ParentHDPath
		{
			get
			{
				return this._ParentHDPath;
			}
			set
			{
				if ((this._ParentHDPath != value))
				{
					this._ParentHDPath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChildHDPath", DbType="NVarChar(61) NOT NULL", CanBeNull=false)]
		public string ChildHDPath
		{
			get
			{
				return this._ChildHDPath;
			}
			set
			{
				if ((this._ChildHDPath != value))
				{
					this._ChildHDPath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string KeyName
		{
			get
			{
				return this._KeyName;
			}
			set
			{
				if ((this._KeyName != value))
				{
					this._KeyName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyNamespace", DbType="NVarChar(1024)")]
		public string KeyNamespace
		{
			get
			{
				return this._KeyNamespace;
			}
			set
			{
				if ((this._KeyNamespace != value))
				{
					this._KeyNamespace = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyLevel", DbType="SmallInt")]
		public System.Nullable<short> KeyLevel
		{
			get
			{
				return this._KeyLevel;
			}
			set
			{
				if ((this._KeyLevel != value))
				{
					this._KeyLevel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiptIndex", DbType="Int")]
		public System.Nullable<int> ReceiptIndex
		{
			get
			{
				return this._ReceiptIndex;
			}
			set
			{
				if ((this._ReceiptIndex != value))
				{
					this._ReceiptIndex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangeIndex", DbType="Int")]
		public System.Nullable<int> ChangeIndex
		{
			get
			{
				return this._ChangeIndex;
			}
			set
			{
				if ((this._ChangeIndex != value))
				{
					this._ChangeIndex = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Subject.vwWallets")]
	public partial class vwWallet
	{
		
		private string _AccountCode;
		
		private string _AccountName;
		
		private string _CashCode;
		
		private short _CoinTypeCode;
		
		public vwWallet()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountCode", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string AccountCode
		{
			get
			{
				return this._AccountCode;
			}
			set
			{
				if ((this._AccountCode != value))
				{
					this._AccountCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string AccountName
		{
			get
			{
				return this._AccountName;
			}
			set
			{
				if ((this._AccountName != value))
				{
					this._AccountName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CashCode", DbType="NVarChar(50)")]
		public string CashCode
		{
			get
			{
				return this._CashCode;
			}
			set
			{
				if ((this._CashCode != value))
				{
					this._CashCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoinTypeCode", DbType="SmallInt NOT NULL")]
		public short CoinTypeCode
		{
			get
			{
				return this._CoinTypeCode;
			}
			set
			{
				if ((this._CoinTypeCode != value))
				{
					this._CoinTypeCode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Cash.vwStatement")]
	public partial class vwCashStatement
	{
		
		private System.Nullable<long> _RowNumber;
		
		private string _SubjectCode;
		
		private string _SubjectName;
		
		private string _EntryDescription;
		
		private System.Nullable<System.DateTime> _TransactOn;
		
		private string _ReferenceCode;
		
		private int _CashEntryTypeCode;
		
		private string _CashEntryType;
		
		private System.Nullable<decimal> _PayIn;
		
		private System.Nullable<decimal> _PayOut;
		
		private System.Nullable<decimal> _Balance;
		
		public vwCashStatement()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowNumber", DbType="BigInt")]
		public System.Nullable<long> RowNumber
		{
			get
			{
				return this._RowNumber;
			}
			set
			{
				if ((this._RowNumber != value))
				{
					this._RowNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubjectCode", DbType="NVarChar(10)")]
		public string SubjectCode
		{
			get
			{
				return this._SubjectCode;
			}
			set
			{
				if ((this._SubjectCode != value))
				{
					this._SubjectCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubjectName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string SubjectName
		{
			get
			{
				return this._SubjectName;
			}
			set
			{
				if ((this._SubjectName != value))
				{
					this._SubjectName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryDescription", DbType="NVarChar(100)")]
		public string EntryDescription
		{
			get
			{
				return this._EntryDescription;
			}
			set
			{
				if ((this._EntryDescription != value))
				{
					this._EntryDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> TransactOn
		{
			get
			{
				return this._TransactOn;
			}
			set
			{
				if ((this._TransactOn != value))
				{
					this._TransactOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReferenceCode", DbType="NVarChar(30)")]
		public string ReferenceCode
		{
			get
			{
				return this._ReferenceCode;
			}
			set
			{
				if ((this._ReferenceCode != value))
				{
					this._ReferenceCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CashEntryTypeCode", DbType="Int NOT NULL")]
		public int CashEntryTypeCode
		{
			get
			{
				return this._CashEntryTypeCode;
			}
			set
			{
				if ((this._CashEntryTypeCode != value))
				{
					this._CashEntryTypeCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CashEntryType", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string CashEntryType
		{
			get
			{
				return this._CashEntryType;
			}
			set
			{
				if ((this._CashEntryType != value))
				{
					this._CashEntryType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayIn", DbType="Decimal(18,5)")]
		public System.Nullable<decimal> PayIn
		{
			get
			{
				return this._PayIn;
			}
			set
			{
				if ((this._PayIn != value))
				{
					this._PayIn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayOut", DbType="Decimal(18,5)")]
		public System.Nullable<decimal> PayOut
		{
			get
			{
				return this._PayOut;
			}
			set
			{
				if ((this._PayOut != value))
				{
					this._PayOut = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balance", DbType="Decimal(18,5)")]
		public System.Nullable<decimal> Balance
		{
			get
			{
				return this._Balance;
			}
			set
			{
				if ((this._Balance != value))
				{
					this._Balance = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Subject.vwListAll")]
	public partial class vwSubjectList
	{
		
		private string _SubjectCode;
		
		private string _SubjectName;
		
		private string _SubjectType;
		
		private string _TaxCode;
		
		private short _CashPolarityCode;
		
		private short _SubjectStatusCode;
		
		private string _CashCode;
		
		public vwSubjectList()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubjectCode", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string SubjectCode
		{
			get
			{
				return this._SubjectCode;
			}
			set
			{
				if ((this._SubjectCode != value))
				{
					this._SubjectCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubjectName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string SubjectName
		{
			get
			{
				return this._SubjectName;
			}
			set
			{
				if ((this._SubjectName != value))
				{
					this._SubjectName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubjectType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SubjectType
		{
			get
			{
				return this._SubjectType;
			}
			set
			{
				if ((this._SubjectType != value))
				{
					this._SubjectType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxCode", DbType="NVarChar(10)")]
		public string TaxCode
		{
			get
			{
				return this._TaxCode;
			}
			set
			{
				if ((this._TaxCode != value))
				{
					this._TaxCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CashPolarityCode", DbType="SmallInt NOT NULL")]
		public short CashPolarityCode
		{
			get
			{
				return this._CashPolarityCode;
			}
			set
			{
				if ((this._CashPolarityCode != value))
				{
					this._CashPolarityCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubjectStatusCode", DbType="SmallInt NOT NULL")]
		public short SubjectStatusCode
		{
			get
			{
				return this._SubjectStatusCode;
			}
			set
			{
				if ((this._SubjectStatusCode != value))
				{
					this._SubjectStatusCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CashCode", DbType="NVarChar(50)")]
		public string CashCode
		{
			get
			{
				return this._CashCode;
			}
			set
			{
				if ((this._CashCode != value))
				{
					this._CashCode = value;
				}
			}
		}
	}
	
	public partial class fnChangeResult
	{
		
		private string _FullHDPath;
		
		private string _AccountCode;
		
		private string _KeyName;
		
		private string _KeyNamespace;
		
		private int _AddressIndex;
		
		private string _PaymentAddress;
		
		private short _ChangeTypeCode;
		
		private string _ChangeType;
		
		private short _ChangeStatusCode;
		
		private string _ChangeStatus;
		
		private string _Note;
		
		private string _InvoiceNumber;
		
		private string _SubjectCode;
		
		private string _SubjectName;
		
		private string _InvoiceType;
		
		private string _InvoiceStatus;
		
		private System.Nullable<short> _CashPolarityCode;
		
		private System.Nullable<decimal> _AmountDue;
		
		private System.Nullable<System.DateTime> _ExpectedOn;
		
		private System.DateTime _UpdatedOn;
		
		private string _UpdatedBy;
		
		private System.DateTime _InsertedOn;
		
		private string _InsertedBy;
		
		private System.Data.Linq.Binary _RowVer;
		
		private System.Nullable<decimal> _Balance;
		
		public fnChangeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullHDPath", DbType="NVarChar(256)", UpdateCheck=UpdateCheck.Never)]
		public string FullHDPath
		{
			get
			{
				return this._FullHDPath;
			}
			set
			{
				if ((this._FullHDPath != value))
				{
					this._FullHDPath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountCode", DbType="NVarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string AccountCode
		{
			get
			{
				return this._AccountCode;
			}
			set
			{
				if ((this._AccountCode != value))
				{
					this._AccountCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyName", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string KeyName
		{
			get
			{
				return this._KeyName;
			}
			set
			{
				if ((this._KeyName != value))
				{
					this._KeyName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyNamespace", DbType="NVarChar(512)", UpdateCheck=UpdateCheck.Never)]
		public string KeyNamespace
		{
			get
			{
				return this._KeyNamespace;
			}
			set
			{
				if ((this._KeyNamespace != value))
				{
					this._KeyNamespace = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressIndex", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int AddressIndex
		{
			get
			{
				return this._AddressIndex;
			}
			set
			{
				if ((this._AddressIndex != value))
				{
					this._AddressIndex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentAddress", DbType="NVarChar(42) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string PaymentAddress
		{
			get
			{
				return this._PaymentAddress;
			}
			set
			{
				if ((this._PaymentAddress != value))
				{
					this._PaymentAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangeTypeCode", DbType="SmallInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public short ChangeTypeCode
		{
			get
			{
				return this._ChangeTypeCode;
			}
			set
			{
				if ((this._ChangeTypeCode != value))
				{
					this._ChangeTypeCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangeType", DbType="NVarChar(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string ChangeType
		{
			get
			{
				return this._ChangeType;
			}
			set
			{
				if ((this._ChangeType != value))
				{
					this._ChangeType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangeStatusCode", DbType="SmallInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public short ChangeStatusCode
		{
			get
			{
				return this._ChangeStatusCode;
			}
			set
			{
				if ((this._ChangeStatusCode != value))
				{
					this._ChangeStatusCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangeStatus", DbType="NVarChar(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string ChangeStatus
		{
			get
			{
				return this._ChangeStatus;
			}
			set
			{
				if ((this._ChangeStatus != value))
				{
					this._ChangeStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(256)", UpdateCheck=UpdateCheck.Never)]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this._Note = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNumber", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string InvoiceNumber
		{
			get
			{
				return this._InvoiceNumber;
			}
			set
			{
				if ((this._InvoiceNumber != value))
				{
					this._InvoiceNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubjectCode", DbType="NVarChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string SubjectCode
		{
			get
			{
				return this._SubjectCode;
			}
			set
			{
				if ((this._SubjectCode != value))
				{
					this._SubjectCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubjectName", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string SubjectName
		{
			get
			{
				return this._SubjectName;
			}
			set
			{
				if ((this._SubjectName != value))
				{
					this._SubjectName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceType", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string InvoiceType
		{
			get
			{
				return this._InvoiceType;
			}
			set
			{
				if ((this._InvoiceType != value))
				{
					this._InvoiceType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceStatus", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string InvoiceStatus
		{
			get
			{
				return this._InvoiceStatus;
			}
			set
			{
				if ((this._InvoiceStatus != value))
				{
					this._InvoiceStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CashPolarityCode", DbType="SmallInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<short> CashPolarityCode
		{
			get
			{
				return this._CashPolarityCode;
			}
			set
			{
				if ((this._CashPolarityCode != value))
				{
					this._CashPolarityCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AmountDue", DbType="Decimal(21,5)", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> AmountDue
		{
			get
			{
				return this._AmountDue;
			}
			set
			{
				if ((this._AmountDue != value))
				{
					this._AmountDue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpectedOn", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> ExpectedOn
		{
			get
			{
				return this._ExpectedOn;
			}
			set
			{
				if ((this._ExpectedOn != value))
				{
					this._ExpectedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOn", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this._UpdatedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="NVarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this._UpdatedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertedOn", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime InsertedOn
		{
			get
			{
				return this._InsertedOn;
			}
			set
			{
				if ((this._InsertedOn != value))
				{
					this._InsertedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertedBy", DbType="NVarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string InsertedBy
		{
			get
			{
				return this._InsertedBy;
			}
			set
			{
				if ((this._InsertedBy != value))
				{
					this._InsertedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowVer", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary RowVer
		{
			get
			{
				return this._RowVer;
			}
			set
			{
				if ((this._RowVer != value))
				{
					this._RowVer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balance", DbType="Decimal(38,5)", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> Balance
		{
			get
			{
				return this._Balance;
			}
			set
			{
				if ((this._Balance != value))
				{
					this._Balance = value;
				}
			}
		}
	}
	
	public partial class fnChangeTxResult
	{
		
		private string _PaymentAddress;
		
		private string _TxId;
		
		private System.DateTime _TransactedOn;
		
		private short _TxStatusCode;
		
		private string _TxStatus;
		
		private decimal _MoneyIn;
		
		private decimal _MoneyOut;
		
		private int _Confirmations;
		
		private string _InsertedBy;
		
		private string _PaymentCodeIn;
		
		private string _PaymentCodeOut;
		
		private string _TxMessage;
		
		public fnChangeTxResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentAddress", DbType="NVarChar(42) NOT NULL", CanBeNull=false)]
		public string PaymentAddress
		{
			get
			{
				return this._PaymentAddress;
			}
			set
			{
				if ((this._PaymentAddress != value))
				{
					this._PaymentAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TxId", DbType="NVarChar(64) NOT NULL", CanBeNull=false)]
		public string TxId
		{
			get
			{
				return this._TxId;
			}
			set
			{
				if ((this._TxId != value))
				{
					this._TxId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactedOn", DbType="DateTime NOT NULL")]
		public System.DateTime TransactedOn
		{
			get
			{
				return this._TransactedOn;
			}
			set
			{
				if ((this._TransactedOn != value))
				{
					this._TransactedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TxStatusCode", DbType="SmallInt NOT NULL")]
		public short TxStatusCode
		{
			get
			{
				return this._TxStatusCode;
			}
			set
			{
				if ((this._TxStatusCode != value))
				{
					this._TxStatusCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TxStatus", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string TxStatus
		{
			get
			{
				return this._TxStatus;
			}
			set
			{
				if ((this._TxStatus != value))
				{
					this._TxStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoneyIn", DbType="Decimal(18,5) NOT NULL")]
		public decimal MoneyIn
		{
			get
			{
				return this._MoneyIn;
			}
			set
			{
				if ((this._MoneyIn != value))
				{
					this._MoneyIn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoneyOut", DbType="Decimal(18,5) NOT NULL")]
		public decimal MoneyOut
		{
			get
			{
				return this._MoneyOut;
			}
			set
			{
				if ((this._MoneyOut != value))
				{
					this._MoneyOut = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Confirmations", DbType="Int NOT NULL")]
		public int Confirmations
		{
			get
			{
				return this._Confirmations;
			}
			set
			{
				if ((this._Confirmations != value))
				{
					this._Confirmations = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertedBy", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string InsertedBy
		{
			get
			{
				return this._InsertedBy;
			}
			set
			{
				if ((this._InsertedBy != value))
				{
					this._InsertedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentCodeIn", DbType="NVarChar(20)")]
		public string PaymentCodeIn
		{
			get
			{
				return this._PaymentCodeIn;
			}
			set
			{
				if ((this._PaymentCodeIn != value))
				{
					this._PaymentCodeIn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentCodeOut", DbType="NVarChar(20)")]
		public string PaymentCodeOut
		{
			get
			{
				return this._PaymentCodeOut;
			}
			set
			{
				if ((this._PaymentCodeOut != value))
				{
					this._PaymentCodeOut = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TxMessage", DbType="NVarChar(50)")]
		public string TxMessage
		{
			get
			{
				return this._TxMessage;
			}
			set
			{
				if ((this._TxMessage != value))
				{
					this._TxMessage = value;
				}
			}
		}
	}
	
	public partial class fnChangeUnassignedResult
	{
		
		private string _AccountCode;
		
		private string _KeyNamespace;
		
		private string _KeyName;
		
		private string _PaymentAddress;
		
		private string _Note;
		
		private System.DateTime _InsertedOn;
		
		private System.DateTime _UpdatedOn;
		
		private System.Nullable<decimal> _Balance;
		
		public fnChangeUnassignedResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountCode", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string AccountCode
		{
			get
			{
				return this._AccountCode;
			}
			set
			{
				if ((this._AccountCode != value))
				{
					this._AccountCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyNamespace", DbType="NVarChar(512)")]
		public string KeyNamespace
		{
			get
			{
				return this._KeyNamespace;
			}
			set
			{
				if ((this._KeyNamespace != value))
				{
					this._KeyNamespace = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string KeyName
		{
			get
			{
				return this._KeyName;
			}
			set
			{
				if ((this._KeyName != value))
				{
					this._KeyName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentAddress", DbType="NVarChar(42) NOT NULL", CanBeNull=false)]
		public string PaymentAddress
		{
			get
			{
				return this._PaymentAddress;
			}
			set
			{
				if ((this._PaymentAddress != value))
				{
					this._PaymentAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(256)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this._Note = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertedOn", DbType="DateTime NOT NULL")]
		public System.DateTime InsertedOn
		{
			get
			{
				return this._InsertedOn;
			}
			set
			{
				if ((this._InsertedOn != value))
				{
					this._InsertedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOn", DbType="DateTime NOT NULL")]
		public System.DateTime UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this._UpdatedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balance", DbType="Decimal(38,5)")]
		public System.Nullable<decimal> Balance
		{
			get
			{
				return this._Balance;
			}
			set
			{
				if ((this._Balance != value))
				{
					this._Balance = value;
				}
			}
		}
	}
	
	public partial class fnKeyAddressesResult
	{
		
		private string _HDPath;
		
		private string _PaymentAddress;
		
		private int _AddressIndex;
		
		public fnKeyAddressesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HDPath", DbType="NVarChar(256)")]
		public string HDPath
		{
			get
			{
				return this._HDPath;
			}
			set
			{
				if ((this._HDPath != value))
				{
					this._HDPath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentAddress", DbType="NVarChar(42) NOT NULL", CanBeNull=false)]
		public string PaymentAddress
		{
			get
			{
				return this._PaymentAddress;
			}
			set
			{
				if ((this._PaymentAddress != value))
				{
					this._PaymentAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressIndex", DbType="Int NOT NULL")]
		public int AddressIndex
		{
			get
			{
				return this._AddressIndex;
			}
			set
			{
				if ((this._AddressIndex != value))
				{
					this._AddressIndex = value;
				}
			}
		}
	}
	
	public partial class fnTxResult
	{
		
		private string _AccountCode;
		
		private string _KeyNamespace;
		
		private string _KeyName;
		
		private string _PaymentAddress;
		
		private short _ChangeTypeCode;
		
		private string _ChangeType;
		
		private short _ChangeStatusCode;
		
		private string _ChangeStatus;
		
		private string _FullHDPath;
		
		private string _TxId;
		
		private System.DateTime _TransactedOn;
		
		private short _TxStatusCode;
		
		private string _TxStatus;
		
		private decimal _MoneyIn;
		
		private decimal _MoneyOut;
		
		private int _Confirmations;
		
		private string _TxMessage;
		
		private string _InsertedBy;
		
		private string _PaymentCodeIn;
		
		private string _PaymentCodeOut;
		
		public fnTxResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountCode", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string AccountCode
		{
			get
			{
				return this._AccountCode;
			}
			set
			{
				if ((this._AccountCode != value))
				{
					this._AccountCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyNamespace", DbType="NVarChar(512)")]
		public string KeyNamespace
		{
			get
			{
				return this._KeyNamespace;
			}
			set
			{
				if ((this._KeyNamespace != value))
				{
					this._KeyNamespace = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyName", DbType="NVarChar(50)")]
		public string KeyName
		{
			get
			{
				return this._KeyName;
			}
			set
			{
				if ((this._KeyName != value))
				{
					this._KeyName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentAddress", DbType="NVarChar(42) NOT NULL", CanBeNull=false)]
		public string PaymentAddress
		{
			get
			{
				return this._PaymentAddress;
			}
			set
			{
				if ((this._PaymentAddress != value))
				{
					this._PaymentAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangeTypeCode", DbType="SmallInt NOT NULL")]
		public short ChangeTypeCode
		{
			get
			{
				return this._ChangeTypeCode;
			}
			set
			{
				if ((this._ChangeTypeCode != value))
				{
					this._ChangeTypeCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangeType", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string ChangeType
		{
			get
			{
				return this._ChangeType;
			}
			set
			{
				if ((this._ChangeType != value))
				{
					this._ChangeType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangeStatusCode", DbType="SmallInt NOT NULL")]
		public short ChangeStatusCode
		{
			get
			{
				return this._ChangeStatusCode;
			}
			set
			{
				if ((this._ChangeStatusCode != value))
				{
					this._ChangeStatusCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangeStatus", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string ChangeStatus
		{
			get
			{
				return this._ChangeStatus;
			}
			set
			{
				if ((this._ChangeStatus != value))
				{
					this._ChangeStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullHDPath", DbType="NVarChar(256)")]
		public string FullHDPath
		{
			get
			{
				return this._FullHDPath;
			}
			set
			{
				if ((this._FullHDPath != value))
				{
					this._FullHDPath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TxId", DbType="NVarChar(64) NOT NULL", CanBeNull=false)]
		public string TxId
		{
			get
			{
				return this._TxId;
			}
			set
			{
				if ((this._TxId != value))
				{
					this._TxId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactedOn", DbType="DateTime NOT NULL")]
		public System.DateTime TransactedOn
		{
			get
			{
				return this._TransactedOn;
			}
			set
			{
				if ((this._TransactedOn != value))
				{
					this._TransactedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TxStatusCode", DbType="SmallInt NOT NULL")]
		public short TxStatusCode
		{
			get
			{
				return this._TxStatusCode;
			}
			set
			{
				if ((this._TxStatusCode != value))
				{
					this._TxStatusCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TxStatus", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string TxStatus
		{
			get
			{
				return this._TxStatus;
			}
			set
			{
				if ((this._TxStatus != value))
				{
					this._TxStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoneyIn", DbType="Decimal(18,5) NOT NULL")]
		public decimal MoneyIn
		{
			get
			{
				return this._MoneyIn;
			}
			set
			{
				if ((this._MoneyIn != value))
				{
					this._MoneyIn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoneyOut", DbType="Decimal(18,5) NOT NULL")]
		public decimal MoneyOut
		{
			get
			{
				return this._MoneyOut;
			}
			set
			{
				if ((this._MoneyOut != value))
				{
					this._MoneyOut = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Confirmations", DbType="Int NOT NULL")]
		public int Confirmations
		{
			get
			{
				return this._Confirmations;
			}
			set
			{
				if ((this._Confirmations != value))
				{
					this._Confirmations = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TxMessage", DbType="NVarChar(50)")]
		public string TxMessage
		{
			get
			{
				return this._TxMessage;
			}
			set
			{
				if ((this._TxMessage != value))
				{
					this._TxMessage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertedBy", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string InsertedBy
		{
			get
			{
				return this._InsertedBy;
			}
			set
			{
				if ((this._InsertedBy != value))
				{
					this._InsertedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentCodeIn", DbType="NVarChar(20)")]
		public string PaymentCodeIn
		{
			get
			{
				return this._PaymentCodeIn;
			}
			set
			{
				if ((this._PaymentCodeIn != value))
				{
					this._PaymentCodeIn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentCodeOut", DbType="NVarChar(20)")]
		public string PaymentCodeOut
		{
			get
			{
				return this._PaymentCodeOut;
			}
			set
			{
				if ((this._PaymentCodeOut != value))
				{
					this._PaymentCodeOut = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
