<?xml version="1.0" encoding="utf-8"?><Database Name="tcNodeDb4_1_1" Class="dbNodeNetworkDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=IAM-01;Initial Catalog=tcNodeDb4_1_1;Integrated Security=True" SettingsObjectName="TradeControl.Node.Properties.Settings" SettingsPropertyName="tcNodeDb4_1_1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="App.tbEth" Member="tbEths">
    <Type Name="tbEth">
      <Column Name="NetworkProvider" Type="System.String" DbType="NVarChar(200) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PublicKey" Type="System.String" DbType="NVarChar(42) NOT NULL" CanBeNull="false" />
      <Column Name="PrivateKey" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="ConsortiumAddress" Type="System.String" DbType="NVarChar(42)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="App.tbUoc" Member="tbUocs">
    <Type Name="tbUoc">
      <Column Name="UnitOfCharge" Type="System.String" DbType="NVarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UocSymbol" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="UocName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="tbUoc_tbOption" Member="tbOptions" ThisKey="UnitOfCharge" OtherKey="UnitOfCharge" Type="tbOption" />
    </Type>
  </Table>
  <Table Name="Invoice.tbItem" Member="tbInvoiceItems">
    <Type Name="tbInvoiceItem">
      <Column Name="InvoiceNumber" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CashCode" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TaxCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="TotalValue" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceValue" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="TaxValue" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="ItemReference" Type="System.String" DbType="NText" CanBeNull="true" />
      <Column Name="RowVer" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Association Name="tbInvoice_tbInvoiceItem" Member="tbInvoice" ThisKey="InvoiceNumber" OtherKey="InvoiceNumber" Type="tbInvoice" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="Invoice.tbMirrorItem" Member="tbMirrorItems">
    <Type Name="tbMirrorItem">
      <Column Name="ContractAddress" Type="System.String" DbType="NVarChar(42) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ChargeCode" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ChargeDescription" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="InvoiceValue" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="TaxValue" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="TaxCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="RowVer" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Association Name="tbMirror_tbMirrorItem" Member="tbInvoiceMirror" ThisKey="ContractAddress" OtherKey="ContractAddress" Type="tbInvoiceMirror" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="Invoice.tbMirrorReference" Member="tbMirrorReferences">
    <Type Name="tbMirrorReference">
      <Column Name="ContractAddress" Type="System.String" DbType="NVarChar(42) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="InvoiceNumber" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="tbMirror_tbMirrorReference" Member="tbInvoiceMirror" ThisKey="ContractAddress" OtherKey="ContractAddress" Type="tbInvoiceMirror" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="tbInvoice_tbMirrorReference" Member="tbInvoice" ThisKey="InvoiceNumber" OtherKey="InvoiceNumber" Type="tbInvoice" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="App.tbTemplate" Member="tbTemplates">
    <Type Name="tbTemplate">
      <Column Name="TemplateName" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StoredProcedure" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="Object.vwNetworkMirrors" Member="vwObjectMirrors">
    <Type Name="vwObjectMirror">
      <Column Name="SubjectCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ObjectCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AllocationCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TransmitStatusCode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="Project.tbAllocation" Member="tbAllocations">
    <Type Name="tbAllocation">
      <Column Name="ContractAddress" Type="System.String" DbType="NVarChar(42) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SubjectCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="AllocationCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AllocationDescription" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ProjectCode" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ProjectTitle" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CashPolarityCode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="UnitOfMeasure" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="UnitOfCharge" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="ProjectStatusCode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ActionOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TaxRate" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="QuantityOrdered" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="QuantityDelivered" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="InsertedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="RowVer" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="UnitCharge" Type="System.Decimal" DbType="Decimal(18,7) NOT NULL" CanBeNull="false" />
      <Association Name="tbSubject_tbAllocation" Member="tbSubject" ThisKey="SubjectCode" OtherKey="SubjectCode" Type="tbSubject" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="Subject.tbSubject" Member="tbSubjects">
    <Type Name="tbSubject">
      <Column Name="SubjectCode" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SubjectName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="SubjectTypeCode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="SubjectStatusCode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="TaxCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="AddressCode" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="AreaCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EmailAddress" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="WebSite" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SubjectSource" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PaymentTerms" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ExpectedDays" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="PaymentDays" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="PayDaysFromMonthEnd" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PayBalance" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NumberOfEmployees" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CompanyNumber" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="VatNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EUJurisdiction" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="BusinessDescription" Type="System.String" DbType="NText" CanBeNull="true" />
      <Column Name="Logo" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
      <Column Name="InsertedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="InsertedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="RowVer" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="TransmitStatusCode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="OpeningBalance" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="Turnover" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Association Name="tbSubject_tbAllocation" Member="tbAllocations" ThisKey="SubjectCode" OtherKey="SubjectCode" Type="tbAllocation" />
      <Association Name="tbSubject_tbOption" Member="tbOptions" ThisKey="SubjectCode" OtherKey="SubjectCode" Type="tbOption" />
      <Association Name="tbSubject_tbOption1" Member="tbOptions1" ThisKey="SubjectCode" OtherKey="MinerAccountCode" Type="tbOption" />
      <Association Name="tbSubject_tbMirror" Member="tbInvoiceMirrors" ThisKey="SubjectCode" OtherKey="SubjectCode" Type="tbInvoiceMirror" />
      <Association Name="tbSubject_tbInvoice" Member="tbInvoices" ThisKey="SubjectCode" OtherKey="SubjectCode" Type="tbInvoice" />
    </Type>
  </Table>
  <Table Name="App.tbOptions" Member="tbOptions">
    <Type Name="tbOption">
      <Column Name="Identifier" Type="System.String" DbType="NVarChar(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IsInitialised" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SubjectCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="RegisterName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DefaultPrintMode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="BucketTypeCode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="BucketIntervalCode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="NetProfitCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="VatCategoryCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="TaxHorizon" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="IsAutoOffsetDays" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="InsertedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="InsertedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="RowVer" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="UnitOfCharge" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="MinerFeeCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MinerAccountCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CoinTypeCode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="HostId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tbSubject_tbOption" Member="tbSubject" ThisKey="SubjectCode" OtherKey="SubjectCode" Type="tbSubject" IsForeignKey="true" />
      <Association Name="tbSubject_tbOption1" Member="tbSubject1" ThisKey="MinerAccountCode" OtherKey="SubjectCode" Type="tbSubject" IsForeignKey="true" />
      <Association Name="tbUoc_tbOption" Member="tbUoc" ThisKey="UnitOfCharge" OtherKey="UnitOfCharge" Type="tbUoc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Project.vwNetworkDeployments" Member="vwProjectDeployments">
    <Type Name="vwProjectDeployment">
      <Column Name="ProjectCode" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SubjectCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ObjectCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ObjectDescription" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ProjectTitle" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ProjectStatusCode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ProjectStatus" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ActionOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="CashPolarityCode" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CashPolarity" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="TaxRate" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="UnitCharge" Type="System.Decimal" DbType="Decimal(18,7) NOT NULL" CanBeNull="false" />
      <Column Name="UnitOfMeasure" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="UnitOfCharge" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="Project.vwNetworkUpdates" Member="vwProjectUpdates">
    <Type Name="vwProjectUpdate">
      <Column Name="ProjectCode" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SubjectCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ObjectCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProjectStatusCode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ProjectStatus" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ActionOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="TaxRate" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="UnitCharge" Type="System.Decimal" DbType="Decimal(18,7) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="Invoice.tbMirror" Member="tbInvoiceMirrors">
    <Type Name="tbInvoiceMirror">
      <Column Name="ContractAddress" Type="System.String" DbType="NVarChar(42) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SubjectCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceTypeCode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceStatusCode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="InvoicedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DueOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UnitOfCharge" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="PaymentTerms" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="InsertedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="RowVer" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="InvoiceValue" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceTax" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="PaidValue" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="PaidTaxValue" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="PaymentAddress" Type="System.String" DbType="NVarChar(42)" CanBeNull="true" />
      <Association Name="tbMirror_tbMirrorItem" Member="tbMirrorItems" ThisKey="ContractAddress" OtherKey="ContractAddress" Type="tbMirrorItem" />
      <Association Name="tbMirror_tbMirrorReference" Member="tbMirrorReference" ThisKey="ContractAddress" OtherKey="ContractAddress" Type="tbMirrorReference" Cardinality="One" />
      <Association Name="tbInvoiceMirror_tbMirrorProject" Member="tbMirrorProjects" ThisKey="ContractAddress" OtherKey="ContractAddress" Type="tbMirrorProject" />
      <Association Name="tbSubject_tbMirror" Member="tbSubject" ThisKey="SubjectCode" OtherKey="SubjectCode" Type="tbSubject" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Invoice.tbMirrorProject" Member="tbMirrorProjects">
    <Type Name="tbMirrorProject">
      <Column Name="ContractAddress" Type="System.String" DbType="NVarChar(42) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProjectCode" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="TaxCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="RowVer" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="InvoiceValue" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="TaxValue" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Association Name="tbInvoiceMirror_tbMirrorProject" Member="tbInvoiceMirror" ThisKey="ContractAddress" OtherKey="ContractAddress" Type="tbInvoiceMirror" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="Invoice.tbProject" Member="tbInvoiceProjects">
    <Type Name="tbInvoiceProject">
      <Column Name="InvoiceNumber" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProjectCode" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CashCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TaxCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="RowVer" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="Quantity" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="TotalValue" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceValue" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="TaxValue" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Association Name="tbInvoice_tbInvoiceProject" Member="tbInvoice" ThisKey="InvoiceNumber" OtherKey="InvoiceNumber" Type="tbInvoice" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="Invoice.tbInvoice" Member="tbInvoices">
    <Type Name="tbInvoice">
      <Column Name="InvoiceNumber" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SubjectCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceTypeCode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceStatusCode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="InvoicedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ExpectedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DueOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PaymentTerms" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="NText" CanBeNull="true" />
      <Column Name="Printed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Spooled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RowVer" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="InvoiceValue" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="TaxValue" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="PaidValue" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="PaidTaxValue" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Association Name="tbInvoice_tbInvoiceItem" Member="tbInvoiceItems" ThisKey="InvoiceNumber" OtherKey="InvoiceNumber" Type="tbInvoiceItem" />
      <Association Name="tbInvoice_tbMirrorReference" Member="tbMirrorReferences" ThisKey="InvoiceNumber" OtherKey="InvoiceNumber" Type="tbMirrorReference" />
      <Association Name="tbInvoice_tbInvoiceProject" Member="tbInvoiceProjects" ThisKey="InvoiceNumber" OtherKey="InvoiceNumber" Type="tbInvoiceProject" />
      <Association Name="tbSubject_tbInvoice" Member="tbSubject" ThisKey="SubjectCode" OtherKey="SubjectCode" Type="tbSubject" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Invoice.vwNetworkDeployments" Member="vwInvoiceDeployments">
    <Type Name="vwInvoiceDeployment">
      <Column Name="InvoiceNumber" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SubjectCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="PaymentPolarity" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="InvoicePolarity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InvoiceStatusCode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DueOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="InvoicedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceValue" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="TaxValue" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="PaymentTerms" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="UnitOfCharge" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="PaymentAddress" Type="System.String" DbType="NVarChar(42)" CanBeNull="true" />
      <Column Name="ContractAddress" Type="System.String" DbType="NVarChar(42)" CanBeNull="true" />
      <Column Name="ContractNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="Invoice.vwNetworkDeploymentItems" Member="vwInvoiceDeploymentItems">
    <Type Name="vwInvoiceDeploymentItem">
      <Column Name="InvoiceNumber" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ChargeCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ChargeDescription" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="InvoiceValue" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="TaxValue" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceQuantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TaxCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="Invoice.vwNetworkUpdates" Member="vwInvoiceUpdates">
    <Type Name="vwInvoiceUpdate">
      <Column Name="InvoiceNumber" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SubjectCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceStatusCode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DueOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PaidValue" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="PaidTaxValue" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="PaymentAddress" Type="System.String" DbType="NVarChar(42)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="Cash.vwNetworkMirrors" Member="vwCashMirrors">
    <Type Name="vwCashMirror">
      <Column Name="SubjectCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CashCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ChargeCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TransmitStatusCode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="App.proc_EventLog" Method="proc_EventLog">
    <Parameter Name="EventMessage" Parameter="eventMessage" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="EventTypeCode" Parameter="eventTypeCode" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="LogCode" Parameter="logCode" Type="System.String" DbType="NVarChar(20)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Object.proc_NetworkUpdated" Method="proc_ObjectNetworkUpdated">
    <Parameter Name="SubjectCode" Parameter="subjectCode" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="AllocationCode" Parameter="allocationCode" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Cash.proc_NetworkUpdated" Method="proc_CashNetworkUpdated">
    <Parameter Name="SubjectCode" Parameter="subjectCode" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="ChargeCode" Parameter="chargeCode" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Invoice.proc_NetworkUpdated" Method="proc_InvoiceNetworkUpdated">
    <Parameter Name="InvoiceNumber" Parameter="invoiceNumber" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Object.proc_Mirror" Method="proc_ObjectMirror">
    <Parameter Name="ObjectCode" Parameter="objectCode" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="SubjectCode" Parameter="subjectCode" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="AllocationCode" Parameter="allocationCode" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Cash.proc_Mirror" Method="proc_CashMirror">
    <Parameter Name="CashCode" Parameter="cashCode" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="SubjectCode" Parameter="subjectCode" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="ChargeCode" Parameter="chargeCode" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Project.proc_NetworkUpdated" Method="proc_ProjectNetworkUpdated">
    <Parameter Name="ProjectCode" Parameter="projectCode" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
</Database>