<?xml version="1.0" encoding="utf-8"?><Database Name="tcNodeDb4_1_1" Class="dbNodeCashDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=IAM-01;Initial Catalog=tcNodeDb4_1_1;Integrated Security=True" SettingsObjectName="TradeControl.Node.Properties.Settings" SettingsPropertyName="tcNodeDb4_1_1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="Cash.vwChangeCollection" Member="vwChangeCollections">
    <Type Name="vwChangeCollection">
      <Column Name="PaymentAddress" Type="System.String" DbType="NVarChar(42) NOT NULL" CanBeNull="false" />
      <Column Name="FullHDPath" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="App.vwTaxCodes" Member="vwTaxCodes">
    <Type Name="vwTaxCode">
      <Column Name="TaxCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TaxDescription" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TaxType" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="Cash.vwCodeLookup" Member="vwCashCodes">
    <Type Name="vwCashCode">
      <Column Name="CashCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CashDescription" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Category" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CashModeCode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="CashMode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="TaxCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="Usr.vwCredentials" Member="vwUserCredentials">
    <Type Name="vwUserCredential">
      <Column Name="UserId" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LogonName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsAdministrator" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="Cash.vwTransferCodeLookup" Member="vwTransferCashCodes">
    <Type Name="vwTransferCashCode">
      <Column Name="CashCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CashDescription" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Category" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CashMode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CashModeCode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="Invoice.vwRegisterSalesOverdue" Member="vwInvoicedReceipts">
    <Type Name="vwInvoicedReceipts">
      <Column Name="InvoiceNumber" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SubjectCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SubjectName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceTypeCode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceStatusCode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceStatus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InvoiceType" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="UnpaidDays" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InvoicedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DueOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ExpectedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceValue" Type="System.Decimal" DbType="Decimal(20,5)" CanBeNull="true" />
      <Column Name="TaxValue" Type="System.Decimal" DbType="Decimal(20,5)" CanBeNull="true" />
      <Column Name="UnpaidValue" Type="System.Decimal" DbType="Decimal(22,5)" CanBeNull="true" />
      <Column Name="PaymentAddress" Type="System.String" DbType="NVarChar(42)" CanBeNull="true" />
      <Column Name="PaymentTerms" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="Invoice.vwRegisterPurchasesOverdue" Member="vwInvoicedPayments">
    <Type Name="vwInvoicedPayments">
      <Column Name="InvoiceNumber" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SubjectCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SubjectName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceTypeCode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceStatusCode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceStatus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InvoiceType" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="UnpaidDays" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InvoicedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DueOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ExpectedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceValue" Type="System.Decimal" DbType="Decimal(20,5)" CanBeNull="true" />
      <Column Name="TaxValue" Type="System.Decimal" DbType="Decimal(20,5)" CanBeNull="true" />
      <Column Name="UnpaidValue" Type="System.Decimal" DbType="Decimal(22,5)" CanBeNull="true" />
      <Column Name="PaymentAddress" Type="System.String" DbType="NVarChar(42)" CanBeNull="true" />
      <Column Name="PaymentTerms" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="Subject.vwNamespace" Member="vwNamespaces">
    <Type Name="vwNamespace">
      <Column Name="AccountCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ParentHDPath" Type="System.String" DbType="NVarChar(61) NOT NULL" CanBeNull="false" />
      <Column Name="ChildHDPath" Type="System.String" DbType="NVarChar(61) NOT NULL" CanBeNull="false" />
      <Column Name="KeyName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KeyNamespace" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="KeyLevel" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ReceiptIndex" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChangeIndex" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="Subject.vwWallets" Member="vwWallets">
    <Type Name="vwWallet">
      <Column Name="AccountCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="AccountName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CashCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CoinTypeCode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="Cash.vwStatement" Member="vwCashStatements">
    <Type Name="vwCashStatement">
      <Column Name="RowNumber" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SubjectCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="SubjectName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="EntryDescription" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TransactOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ReferenceCode" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="CashEntryTypeCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CashEntryType" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PayIn" Type="System.Decimal" DbType="Decimal(18,5)" CanBeNull="true" />
      <Column Name="PayOut" Type="System.Decimal" DbType="Decimal(18,5)" CanBeNull="true" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(18,5)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="Subject.vwListAll" Member="vwSubjectLists">
    <Type Name="vwSubjectList">
      <Column Name="SubjectCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SubjectName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="SubjectType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TaxCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CashPolarityCode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="SubjectStatusCode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="CashCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="App.proc_EventLog" Method="proc_EventLog">
    <Parameter Name="EventMessage" Parameter="eventMessage" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="EventTypeCode" Parameter="eventTypeCode" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="LogCode" Parameter="logCode" Type="System.String" DbType="NVarChar(20)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Cash.fnChange" Method="fnChange" IsComposable="true">
    <Parameter Name="AccountCode" Parameter="accountCode" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="KeyName" Parameter="keyName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ChangeTypeCode" Parameter="changeTypeCode" Type="System.Int16" DbType="SmallInt" />
    <ElementType Name="fnChangeResult">
      <Column Name="FullHDPath" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="AccountCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="KeyName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KeyNamespace" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="AddressIndex" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PaymentAddress" Type="System.String" DbType="NVarChar(42) NOT NULL" CanBeNull="false" />
      <Column Name="ChangeTypeCode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ChangeType" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ChangeStatusCode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ChangeStatus" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="InvoiceNumber" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="SubjectCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="SubjectName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="InvoiceType" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="InvoiceStatus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CashPolarityCode" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="AmountDue" Type="System.Decimal" DbType="Decimal(21,5)" CanBeNull="true" />
      <Column Name="ExpectedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="InsertedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="InsertedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RowVer" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(38,5)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Cash.fnChangeTx" Method="fnChangeTx" IsComposable="true">
    <Parameter Name="PaymentAddress" Parameter="paymentAddress" Type="System.String" DbType="NVarChar(42)" />
    <ElementType Name="fnChangeTxResult">
      <Column Name="PaymentAddress" Type="System.String" DbType="NVarChar(42) NOT NULL" CanBeNull="false" />
      <Column Name="TxId" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="TransactedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TxStatusCode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="TxStatus" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MoneyIn" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="MoneyOut" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="Confirmations" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InsertedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PaymentCodeIn" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="PaymentCodeOut" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="TxMessage" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Cash.fnChangeUnassigned" Method="fnChangeUnassigned" IsComposable="true">
    <Parameter Name="AccountCode" Parameter="accountCode" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="fnChangeUnassignedResult">
      <Column Name="AccountCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="KeyNamespace" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="KeyName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PaymentAddress" Type="System.String" DbType="NVarChar(42) NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="InsertedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(38,5)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Cash.fnKeyAddresses" Method="fnKeyAddresses" IsComposable="true">
    <Parameter Name="AccountCode" Parameter="accountCode" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="KeyName" Parameter="keyName" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="fnKeyAddressesResult">
      <Column Name="HDPath" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PaymentAddress" Type="System.String" DbType="NVarChar(42) NOT NULL" CanBeNull="false" />
      <Column Name="AddressIndex" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="Cash.fnKeyNameBalance" Method="fnKeyNameBalance" IsComposable="true">
    <Parameter Name="AccountCode" Parameter="accountCode" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="KeyName" Parameter="keyName" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Double" />
  </Function>
  <Function Name="Cash.fnNamespaceBalance" Method="fnNamespaceBalance" IsComposable="true">
    <Parameter Name="AccountCode" Parameter="accountCode" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="KeyName" Parameter="keyName" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Double" />
  </Function>
  <Function Name="Cash.fnTx" Method="fnTx" IsComposable="true">
    <Parameter Name="AccountCode" Parameter="accountCode" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="KeyName" Parameter="keyName" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="fnTxResult">
      <Column Name="AccountCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="KeyNamespace" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="KeyName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PaymentAddress" Type="System.String" DbType="NVarChar(42) NOT NULL" CanBeNull="false" />
      <Column Name="ChangeTypeCode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ChangeType" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ChangeStatusCode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ChangeStatus" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="FullHDPath" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="TxId" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="TransactedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TxStatusCode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="TxStatus" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MoneyIn" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="MoneyOut" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="Confirmations" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TxMessage" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InsertedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PaymentCodeIn" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="PaymentCodeOut" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Subject.proc_AccountKeyRename" Method="proc_AccountKeyRename">
    <Parameter Name="AccountCode" Parameter="accountCode" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="OldKeyName" Parameter="oldKeyName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="NewKeyName" Parameter="newKeyName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="KeyNamespace" Parameter="keyNamespace" Type="System.String" DbType="NVarChar(1024)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Subject.proc_AccountKeyDelete" Method="proc_AccountKeyDelete">
    <Parameter Name="AccountCode" Parameter="accountCode" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="KeyName" Parameter="keyName" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Subject.proc_AccountKeyAdd" Method="proc_AccountKeyAdd">
    <Parameter Name="AccountCode" Parameter="accountCode" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="ParentName" Parameter="parentName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ChildName" Parameter="childName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ChildHDPath" Parameter="childHDPath" Type="System.String" DbType="NVarChar(50)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Subject.proc_BalanceToPay" Method="proc_BalanceToPay">
    <Parameter Name="SubjectCode" Parameter="subjectCode" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Balance" Parameter="balance" Type="System.Decimal" DbType="Decimal(18,5)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Cash.proc_ChangeAddressIndex" Method="proc_ChangeAddressIndex">
    <Parameter Name="AccountCode" Parameter="accountCode" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="KeyName" Parameter="keyName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ChangeTypeCode" Parameter="changeTypeCode" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="AddressIndex" Parameter="addressIndex" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Cash.proc_ChangeTxAdd" Method="proc_ChangeTxAdd">
    <Parameter Name="PaymentAddress" Parameter="paymentAddress" Type="System.String" DbType="NVarChar(42)" />
    <Parameter Name="TxId" Parameter="txId" Type="System.String" DbType="NVarChar(64)" />
    <Parameter Name="TxStatusCode" Parameter="txStatusCode" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="MoneyIn" Parameter="moneyIn" Type="System.Decimal" DbType="Decimal(18,5)" />
    <Parameter Name="Confirmations" Parameter="confirmations" Type="System.Int32" DbType="Int" />
    <Parameter Name="TxMessage" Parameter="txMessage" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Cash.proc_ChangeAssign" Method="proc_ChangeAssign">
    <Parameter Name="AccountCode" Parameter="accountCode" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="KeyName" Parameter="keyName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="PaymentAddress" Parameter="paymentAddress" Type="System.String" DbType="NVarChar(42)" />
    <Parameter Name="InvoiceNumber" Parameter="invoiceNumber" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Note" Parameter="note" Type="System.String" DbType="NVarChar(256)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Cash.proc_ChangeDelete" Method="proc_ChangeDelete">
    <Parameter Name="PaymentAddress" Parameter="paymentAddress" Type="System.String" DbType="NVarChar(42)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Cash.proc_ChangeNew" Method="proc_ChangeNew">
    <Parameter Name="AccountCode" Parameter="accountCode" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="KeyName" Parameter="keyName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ChangeTypeCode" Parameter="changeTypeCode" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="PaymentAddress" Parameter="paymentAddress" Type="System.String" DbType="NVarChar(42)" />
    <Parameter Name="AddressIndex" Parameter="addressIndex" Type="System.Int32" DbType="Int" />
    <Parameter Name="InvoiceNumber" Parameter="invoiceNumber" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Note" Parameter="note" Type="System.String" DbType="NVarChar(256)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Cash.proc_ChangeNote" Method="proc_ChangeNote">
    <Parameter Name="PaymentAddress" Parameter="paymentAddress" Type="System.String" DbType="NVarChar(42)" />
    <Parameter Name="Note" Parameter="note" Type="System.String" DbType="NVarChar(256)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Cash.proc_PayAccrual" Method="proc_PayAccrual">
    <Parameter Name="PaymentCode" Parameter="paymentCode" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Cash.proc_PaymentPost" Method="proc_PaymentPost">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Cash.proc_TxPayOutTransfer" Method="proc_TxPayOutTransfer">
    <Parameter Name="PaymentAddress" Parameter="paymentAddress" Type="System.String" DbType="NVarChar(42)" />
    <Parameter Name="TxId" Parameter="txId" Type="System.String" DbType="NVarChar(64)" />
    <Parameter Name="Spent" Parameter="spent" Type="System.Decimal" DbType="Decimal(18,5)" />
    <Parameter Name="MinerFee" Parameter="minerFee" Type="System.Decimal" DbType="Decimal(18,5)" />
    <Parameter Name="CashCode" Parameter="cashCode" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="PaymentReference" Parameter="paymentReference" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Cash.proc_TxPayAccount" Method="proc_TxPayAccount">
    <Parameter Name="PaymentAddress" Parameter="paymentAddress" Type="System.String" DbType="NVarChar(42)" />
    <Parameter Name="TxId" Parameter="txId" Type="System.String" DbType="NVarChar(64)" />
    <Parameter Name="Spent" Parameter="spent" Type="System.Decimal" DbType="Decimal(18,5)" />
    <Parameter Name="MinerFee" Parameter="minerFee" Type="System.Decimal" DbType="Decimal(18,5)" />
    <Parameter Name="SubjectCode" Parameter="subjectCode" Type="System.String" DbType="NVarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Cash.proc_TxPayIn" Method="proc_TxPayIn">
    <Parameter Name="AccountCode" Parameter="accountCode" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="PaymentAddress" Parameter="paymentAddress" Type="System.String" DbType="NVarChar(42)" />
    <Parameter Name="TxId" Parameter="txId" Type="System.String" DbType="NVarChar(64)" />
    <Parameter Name="SubjectCode" Parameter="subjectCode" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="CashCode" Parameter="cashCode" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="PaidOn" Parameter="paidOn" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PaymentReference" Parameter="paymentReference" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="PaymentCode" Parameter="paymentCode" Type="System.String" DbType="NVarChar(20)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Cash.proc_TxPayInChange" Method="proc_TxPayInChange">
    <Parameter Name="AccountCode" Parameter="accountCode" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="PaymentAddress" Parameter="paymentAddress" Type="System.String" DbType="NVarChar(42)" />
    <Parameter Name="TxId" Parameter="txId" Type="System.String" DbType="NVarChar(64)" />
    <Parameter Name="SubjectCode" Parameter="subjectCode" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="CashCode" Parameter="cashCode" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="PaymentReference" Parameter="paymentReference" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Cash.proc_TxPayOutInvoice" Method="proc_TxPayOutInvoice">
    <Parameter Name="SubjectCode" Parameter="subjectCode" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="CashCode" Parameter="cashCode" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="TaxCode" Parameter="taxCode" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="ItemReference" Parameter="itemReference" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="PaidOutValue" Parameter="paidOutValue" Type="System.Decimal" DbType="Decimal(18,5)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Cash.proc_TxPayOutMisc" Method="proc_TxPayOutMisc">
    <Parameter Name="PaymentAddress" Parameter="paymentAddress" Type="System.String" DbType="NVarChar(42)" />
    <Parameter Name="TxId" Parameter="txId" Type="System.String" DbType="NVarChar(64)" />
    <Parameter Name="Spent" Parameter="spent" Type="System.Decimal" DbType="Decimal(18,5)" />
    <Parameter Name="MinerFee" Parameter="minerFee" Type="System.Decimal" DbType="Decimal(18,5)" />
    <Parameter Name="SubjectCode" Parameter="subjectCode" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="CashCode" Parameter="cashCode" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="TaxCode" Parameter="taxCode" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="PaymentReference" Parameter="paymentReference" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Subject.proc_WalletInitialise" Method="proc_WalletInitialise">
    <Return Type="System.Int32" />
  </Function>
</Database>